name: 'Google Indexing Action'
description: '🚀 GitHub Action to get your site indexed on Google in less than 48 hours.'
author: 'Robin Genz'

# Define your inputs here.
inputs:
  siteUrl:
    description: 'The domain or site URL of the site to be indexed.'
    required: true
  gcpServiceAccountKey:
    description: 'The GCP service account key in JSON format.'
    required: true

runs:
  using: node20
  main: dist/index.mjs
